document.addEventListener("DOMContentLoaded",()=>{
const esc=x=>String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const lang=localStorage.getItem("revaLang")||"en";
const agents=[
{id:"medical",icon:"✚",title:{en:"Medical AI Agent",ar:"وكيل AI طبي",fr:"Agent IA médical"},text:{en:"First intake, FAQ routing, appointment preparation and knowledge assistance.",ar:"استقبال أولي، توجيه الأسئلة، تجهيز المواعيد ومساعدة الموظفين في المعرفة.",fr:"Pré-admission, routage des FAQ, préparation de rendez-vous et aide aux connaissances."},demo:"medical"},
{id:"realty",icon:"⌂",title:{en:"Real Estate AI Agent",ar:"وكيل AI عقاري",fr:"Agent IA immobilier"},text:{en:"Lead qualification, data collection, listing summaries and follow-up.",ar:"تأهيل العملاء المحتملين، جمع البيانات، تلخيص العقارات ومتابعة العملاء.",fr:"Qualification des prospects, collecte de leads, résumés d'annonces et relances."},demo:"realty"},
{id:"hotel",icon:"⌂",title:{en:"Hotel AI Agent",ar:"وكيل AI فندقي",fr:"Agent IA hôtelier"},text:{en:"Guest FAQs, room discovery, concierge services and booking requests.",ar:"الأسئلة الشائعة للنزلاء، اكتشاف الغرف، خدمات الكونسيرج وجمع طلبات الحجز.",fr:"FAQ clients, découverte des chambres, conciergerie et demandes de réservation."},demo:"hotel"}
];
const influencers=[
{name:"Zayn",role:"Technology & Lifestyle AI Creator",image:"zayn.jpg",video:"",agent_id:"hotel"},
{name:"Maya",role:"Beauty & Travel AI Creator",image:"maya.jpg",video:"",agent_id:"realty"},
{name:"Lian",role:"AI Creator",image:"lian.jpg",video:"",agent_id:"medical"}
];
if(document.getElementById("agentCards"))document.getElementById("agentCards").innerHTML=agents.map(x=>`<article><i>${esc(x.icon)}</i><h3>${esc(x.title?.[lang]||x.title.en)}</h3><p>${esc(x.text?.[lang]||x.text.en)}</p><a class="btn" href="demos.html#${encodeURIComponent(x.demo)}">Open Demo →</a></article>`).join("");
if(document.getElementById("influencerGrid"))document.getElementById("influencerGrid").innerHTML=influencers.map(x=>`<article class="influencer"><img src="${esc(x.image)}" alt="${esc(x.name)}"><div class="inf-body"><div class="eyebrow">${esc(x.name)} · ${esc(x.role)}</div><h2>${esc(x.name)}</h2><p>AI creator profile for campaigns, storytelling and social content.</p>${x.video?`<video src="${esc(x.video)}" controls preload="metadata" poster="${esc(x.image)}" style="width:100%;max-height:360px;border-radius:16px"></video>`:""}<span class="tag">${esc(x.role)}</span></div></article>`).join("");
if(document.getElementById("adGrid")){const amap=Object.fromEntries(agents.map(a=>[a.id,a]));document.getElementById("adGrid").innerHTML=influencers.map(x=>{const a=amap[x.agent_id]||{};const title=a.title?.[lang]||a.title?.en||"AI Agent";const text=a.text?.[lang]||a.text?.en||"";const media=x.video?`<video src="${esc(x.video)}" controls preload="metadata" poster="${esc(x.image)}"></video>`:`<img src="${esc(x.image)}" alt="${esc(x.name)}" style="width:100%;height:100%;min-height:360px;object-fit:cover;display:block"><div class="media-note">${lang==="ar"?"الفيديو يمكن ربطه لاحقاً عبر التخزين السحابي.":lang==="fr"?"La vidéo pourra être reliée plus tard via un stockage cloud.":"Video can be connected later through cloud storage."}</div>`;return `<article class="ad-card"><div class="ad-media">${media}</div><div class="ad-copy"><div class="eyebrow">${esc(x.name)} · ${esc(x.role)}</div><h2>${esc(title)}</h2><p>${esc(text)}</p><a class="btn primary" href="demos.html#${encodeURIComponent(a.demo||"")}">${lang==="ar"?"جرّب الوكيل ←":lang==="fr"?"Tester l’agent →":"Try the AI Agent →"}</a></div></article>`}).join("")}
});
