const $=s=>document.querySelector(s), toast=m=>{let x=$("#toast");x.textContent=m;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}, api=async(u,o={})=>{let r=await fetch(u,{headers:{"Content-Type":"application/json",...(o.headers||{})},...o});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d};
let content={}, agents=[], influencers=[];
async function boot(){const s=await api("/api/session");if(s.authenticated)showApp();else $("#login").hidden=false}
function showApp(){$("#login").hidden=true;$("#app").hidden=false;loadContent();loadAgents();loadInfluencers()}
$("#loginBtn").onclick=async()=>{try{await api("/api/login",{method:"POST",body:JSON.stringify({email:$("#user").value,password:$("#pass").value})});showApp()}catch(e){toast(e.message)}};
$("#logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tabpage").forEach(x=>x.hidden=true);$("#"+b.dataset.tab).hidden=false});
function flatten(o,p="",out=[]){for(const [k,v] of Object.entries(o||{})){const key=p?p+"."+k:k;if(v&&typeof v==="object"&&!Array.isArray(v))flatten(v,key,out);else out.push([key,v])}return out}
function setVal(o,k,v){const p=k.split(".");let x=o;for(let i=0;i<p.length-1;i++)x=x[p[i]]||(x[p[i]]={});x[p.at(-1)]=v}
async function loadContent(){content=await api("/api/content");renderContent()}
function renderContent(){const l=$("#lang").value, rows=flatten(content[l]||{});$("#contentFields").innerHTML=rows.map(([k,v])=>`<div class="editor"><label>${k}</label><textarea data-k="${k}">${String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;")}</textarea></div>`).join("")}
$("#lang").onchange=renderContent;$("#loadContent").onclick=loadContent;
$("#saveContent").onclick=async()=>{const l=$("#lang").value;content[l]=content[l]||{};document.querySelectorAll("#contentFields [data-k]").forEach(e=>setVal(content[l],e.dataset.k,e.value));await api("/api/content/"+l,{method:"PUT",body:JSON.stringify(content[l])});toast("Published to all visitors.")}
async function loadAgents(){agents=await api("/api/agents");renderAgents()}
function renderAgents(){$("#agentsList").innerHTML=agents.map((a,i)=>`<div class="card editor"><div style="font-size:38px;text-align:center">${a.icon||"✦"}</div><div><input data-a="${i}" data-k="icon" value="${esc(a.icon||"")}"><input data-a="${i}" data-k="id" value="${esc(a.id)}"><input data-a="${i}" data-k="enTitle" value="${esc(a.title?.en||"")}"><textarea data-a="${i}" data-k="enText">${esc(a.text?.en||"")}</textarea><input data-a="${i}" data-k="arTitle" value="${esc(a.title?.ar||"")}"><textarea data-a="${i}" data-k="arText">${esc(a.text?.ar||"")}</textarea><input data-a="${i}" data-k="frTitle" value="${esc(a.title?.fr||"")}"><textarea data-a="${i}" data-k="frText">${esc(a.text?.fr||"")}</textarea></div><div><button onclick="saveAgent(${i})">Save</button><button class="danger" onclick="deleteAgent('${a.id}')">Delete</button></div></div>`).join("")}
function esc(x){return String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}
window.saveAgent=async i=>{const a=JSON.parse(JSON.stringify(agents[i]));document.querySelectorAll(`[data-a="${i}"]`).forEach(e=>{const k=e.dataset.k;if(k==="icon")a.icon=e.value;if(k==="enTitle")a.title.en=e.value;if(k==="enText")a.text.en=e.value;if(k==="arTitle")a.title.ar=e.value;if(k==="arText")a.text.ar=e.value;if(k==="frTitle")a.title.fr=e.value;if(k==="frText")a.text.fr=e.value});agents[i]=await api("/api/agents/"+a.id,{method:"PUT",body:JSON.stringify(a)});renderAgents();toast("Agent published.")};
window.deleteAgent=async id=>{if(confirm("Delete this AI Agent?")){await api("/api/agents/"+id,{method:"DELETE"});loadAgents();toast("Agent deleted.")}};
$("#newAgent").onclick=async()=>{const a=await api("/api/agents",{method:"POST",body:JSON.stringify({icon:"✦",title:{en:"New AI Agent",ar:"وكيل AI جديد",fr:"Nouvel agent IA"},text:{en:"New agent description.",ar:"وصف الوكيل الجديد.",fr:"Description du nouvel agent."}})});agents.push(a);renderAgents();toast("New agent added.")};
async function loadInfluencers(){influencers=await api("/api/influencers");renderInfluencers()}
function renderInfluencers(){$("#influencersList").innerHTML=influencers.map((x,i)=>`<div class="card editor"><div>${x.image?`<img src="${esc(x.image)}" onerror="this.style.opacity=.25">`:''}${x.video?`<video src="${esc(x.video)}" controls style="width:100%;max-height:220px"></video>`:''}</div><div><input data-i="${i}" data-k="name" value="${esc(x.name)}"><input data-i="${i}" data-k="role" value="${esc(x.role)}"><input data-i="${i}" data-k="image" value="${esc(x.image)}"><label class="upload">Upload portrait <input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-upload-image="${i}"></label><input data-i="${i}" data-k="video" value="${esc(x.video||'')}" placeholder="Video URL"><label class="upload">Upload video <input type="file" accept="video/mp4,video/webm,video/quicktime" data-upload-video="${i}"></label></div><div><button onclick="saveInfluencer(${i})">Save</button><button class="danger" onclick="deleteInfluencer('${x.id}')">Delete</button></div></div>`).join("")}
document.addEventListener("change",async e=>{const kind=e.target.dataset.uploadImage?'image':(e.target.dataset.uploadVideo?'video':null);if(!kind)return;const i=e.target.dataset.uploadImage??e.target.dataset.uploadVideo,f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append("file",f);const r=await fetch("/api/media/upload",{method:"POST",body:fd});const d=await r.json();if(r.ok){influencers[i][kind==='image'?'image':'video']=d.url;renderInfluencers();toast((kind==='image'?'Portrait':'Video')+' uploaded.')}else toast(d.error||"Upload failed")});
window.saveInfluencer=async i=>{const x={...influencers[i]};document.querySelectorAll(`[data-i="${i}"]`).forEach(e=>x[e.dataset.k]=e.value);influencers[i]=await api("/api/influencers/"+x.id,{method:"PUT",body:JSON.stringify(x)});renderInfluencers();toast("Influencer published.")};
window.deleteInfluencer=async id=>{if(confirm("Delete this influencer?")){await api("/api/influencers/"+id,{method:"DELETE"});loadInfluencers();toast("Influencer deleted.")}};
$("#newInfluencer").onclick=async()=>{const x=await api("/api/influencers",{method:"POST",body:JSON.stringify({name:"New Influencer",role:"AI Creator",image:"",video:""})});influencers.push(x);renderInfluencers();toast("Influencer added.")};
$("#downloadBackup").onclick=async()=>{const b=await api("/api/backup");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:"application/json"}));a.download="reva-v11-full-backup.json";a.click()};
$("#backupFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=JSON.parse(await f.text());await api("/api/backup",{method:"POST",body:JSON.stringify(b)});$("#status").textContent="Backup restored successfully.";loadContent();loadAgents();loadInfluencers()}catch(err){$("#status").textContent=err.message}};
boot();


async function loadPages(){try{const a=await api("/api/pages/all");pages=a;renderPages()}catch(e){toast(e.message)}}
let pages=[];
function renderPages(){$("#pagesList").innerHTML=pages.map((p,i)=>`<div class="card editor"><div><input data-p="${i}" data-k="slug" value="${esc(p.slug)}"><select data-p="${i}" data-k="template"><option value="standard" ${p.template==='standard'?'selected':''}>Standard</option></select><label><input type="checkbox" data-p="${i}" data-k="published" ${p.published?'checked':''}> Published</label><a href="/p/${encodeURIComponent(p.slug)}" target="_blank">View page ↗</a></div><div><input data-p="${i}" data-k="enTitle" value="${esc(p.title?.en||'')}"><textarea data-p="${i}" data-k="enBody" placeholder="English body">${esc(p.body?.en||'')}</textarea><input data-p="${i}" data-k="arTitle" value="${esc(p.title?.ar||'')}"><textarea data-p="${i}" data-k="arBody" placeholder="Arabic body">${esc(p.body?.ar||'')}</textarea><input data-p="${i}" data-k="frTitle" value="${esc(p.title?.fr||'')}"><textarea data-p="${i}" data-k="frBody" placeholder="French body">${esc(p.body?.fr||'')}</textarea></div><div><button onclick="savePage(${i})">Save / Publish</button><button class="danger" onclick="deletePage('${p.id}')">Delete</button></div></div>`).join("")}
window.savePage=async i=>{const p=JSON.parse(JSON.stringify(pages[i]));document.querySelectorAll(`[data-p="${i}"]`).forEach(e=>{const k=e.dataset.k;if(k==='slug')p.slug=e.value;if(k==='template')p.template=e.value;if(k==='published')p.published=e.checked;if(k==='enTitle')p.title.en=e.value;if(k==='enBody')p.body.en=e.value;if(k==='arTitle')p.title.ar=e.value;if(k==='arBody')p.body.ar=e.value;if(k==='frTitle')p.title.fr=e.value;if(k==='frBody')p.body.fr=e.value});await api('/api/pages/'+p.id,{method:'PUT',body:JSON.stringify(p)});await loadPages();toast('Page saved.')}
window.deletePage=async id=>{if(confirm('Delete this page?')){await api('/api/pages/'+id,{method:'DELETE'});loadPages();toast('Page deleted.')}}
$("#newPage").onclick=async()=>{const p=await api('/api/pages',{method:'POST',body:JSON.stringify({slug:'new-page-'+Date.now(),title:{en:'New Page',ar:'صفحة جديدة',fr:'Nouvelle page'},body:{en:'',ar:'',fr:''},template:'standard',published:false})});pages.push(p);renderPages();toast('New future page created.')}

async function loadAdmins(){try{const a=await api("/api/admins");$("#adminsList").innerHTML=a.map(x=>`<div class="card"><div><b>${esc(x.email)}</b><div>${esc(x.role)} · ${x.active?"active":"disabled"}</div></div><div><select onchange="roleAdmin('${x.id}',this.value)"><option ${x.role==="viewer"?"selected":""}>viewer</option><option ${x.role==="media"?"selected":""}>media</option><option ${x.role==="editor"?"selected":""}>editor</option><option ${x.role==="owner"?"selected":""}>owner</option></select><button onclick="toggleAdmin('${x.id}',${x.active})">${x.active?"Disable":"Enable"}</button></div></div>`).join("")}catch(e){toast(e.message)}}
window.roleAdmin=async(id,role)=>{await api("/api/admins/"+id,{method:"PATCH",body:JSON.stringify({role})});loadAdmins();toast("Role updated.")};
window.toggleAdmin=async(id,active)=>{await api("/api/admins/"+id,{method:"PATCH",body:JSON.stringify({active:!active})});loadAdmins();toast("Account updated.")};
$("#addAdmin").onclick=async()=>{await api("/api/admins",{method:"POST",body:JSON.stringify({email:$("#newEmail").value,password:$("#newPassword").value,role:$("#newRole").value})});$("#newEmail").value="";$("#newPassword").value="";loadAdmins();toast("Admin created.")};
async function loadAudit(){try{const a=await api("/api/audit");$("#auditList").innerHTML=a.map(x=>`<div class="editor"><b>${esc(x.action)}</b> · ${esc(x.entity_type||"")} · ${esc(x.email||"system")}<br><small>${esc(x.created_at)}</small></div>`).join("")}catch(e){toast(e.message)}}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="pages")loadPages();if(b.dataset.tab==="admins")loadAdmins();if(b.dataset.tab==="audit")loadAudit()}));
